GET http://127.0.0.1:81

POST http://127.0.0.1:81 HTTP/1.1

content-type: application/json

{
    "_id": 5,
    "accountID": 1,
    "userName": "Anakin Skywalker",
    "titleID": 2,
    "userAction": "Paused",
    "dateTime": "2022-03-21",
    "pointOfInteraction": "00:10:23",
    "typeOfInteraction": "Stopped"
}